local M = {}

local pretty = {
    dap = {
        Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
        Breakpoint = " ",
        BreakpointCondition = " ",
        BreakpointRejected = { " ", "DiagnosticError" },
        LogPoint = ".>",
    },
    diagnostics = {
        Error = " ",
        Warn = " ",
        Hint = " ",
        Info = " ",
    },
    git = {
        added = " ",
        modified = " ",
        removed = " ",
        branch = " ", -- 
    },
    gitsigns = {
        signs = {
            add = "┃",
            change = "┃",
            delete = "_",
            topdelete = "‾",
            changedelete = "~",
            untracked = "┆",
        },
        signs_staged = {
            add = "┃",
            change = "┃",
            delete = "_",
            topdelete = "‾",
            changedelete = "~",
            untracked = "┆",
        },
    },
    indent = {
        char = "▏",
    },
    folder = {
        closed = " ",
        opened = " ",
    },
    --   פּ ﯟ     some other good icons
    kinds = {
        Array = " ",
        Boolean = " ",
        Class = "󰠱",
        Color = "",
        Constant = "󰏿",
        Constructor = "", -- ""
        Copilot = " ",
        Enum = " ",
        EnumMember = " ",
        Event = " ",
        Field = "󰜢 ",
        File = " ",
        Folder = " ",
        Formatter = "󰛘",
        Function = " ",
        Interface = " ",
        Key = " ",
        Keyword = " ",
        Linter = "",
        LSP = " ",
        Method = "m",
        Module = " ",
        Namespace = " ",
        Null = " ",
        Number = " ",
        Object = " ",
        Operator = " ",
        Package = " ",
        Property = "󰜢 ",
        Reference = " ",
        Snippet = " ",
        String = " ",
        Struct = " ",
        Text = " ",
        TypeParameter = " ",
        Unit = " ",
        Value = " ",
        Variable = "󰀫 ",
    },
    luasnip = {
        choice_node = "●",
    },
    mason = {
        package_installed = "✓",
        package_pending = "➜",
        package_uninstalled = "✗",
    },
    render_markdown = {
        heading = {
            icons = { "󰲡 ", "󰲣 ", "󰲥 ", "󰲧 ", "󰲩 ", "󰲫 " },
            signs = { "󰫎 " },
            above = "▄",
            below = "▀",
        },
        code = {
            language_border = "█",
            above = "▄",
            below = "▀",
        },
        dash = "─",
        bullet = { "●", "○", "◆", "◇" },
        checkbox = {
            unchecked = "󰄱 ",
            checked = "󰱒 ",
        },
        custom = {
            todo = "󰥔 ",
        },
        quote = "▋",
        table = { "┌", "┬", "┐", "├", "┼", "┤", "└", "┴", "┘", "│", "─" },
        callout = {
            note = "󰋽 ",
            tip = "󰌶 ",
            important = "󰅾 ",
            warning = "󰀪 ",
            caution = "󰳦 ",
            abstract = "󰨸 ",
            summary = "󰨸 ",
            tldr = "󰨸 ",
            info = "󰋽 ",
            todo = "󰗡 ",
            hint = "󰌶 ",
            success = "󰄬 ",
            check = "󰄬 ",
            done = "󰄬 ",
            question = "󰘥 ",
            help = "󰘥 ",
            faq = "󰘥 ",
            attention = "󰀪 ",
            failure = "󰅖 ",
            fail = "󰅖 ",
            missing = "󰅖 ",
            danger = "󱐌 ",
            error = "󱐌 ",
            bug = "󰨰 ",
            example = "󰉹 ",
            quote = "󱆨 ",
            cite = "󱆨 ",
        },
        link = {
            footnote = "󰯔 ",
            image = "󰥶 ",
            email = "󰀓 ",
            hyperlink = "󰌹 ",
            wiki = "󱗖 ",
            custom = {
                web = "󰖟 ",
                apple = " ",
                discord = "󰙯 ",
                github = "󰊤 ",
                gitlab = "󰮠 ",
                google = "󰊭 ",
                hackernews = " ",
                linkedin = "󰌻 ",
                microsoft = " ",
                neovim = " ",
                reddit = "󰑍 ",
                slack = "󰒱 ",
                stackoverflow = "󰓌 ",
                steam = " ",
                twitter = " ",
                wikipedia = "󰖬 ",
                x = " ",
                youtube = "󰗃 ",
                youtube_short = "󰗃 ",
            },
        },
        indent = "▎",
    },
    statusline = {
        sep = "│",
    },
    winbar = {
        modified = "[+]",
        readonly = "",
        lsp = " ",
    },
}

local plain = {
    dap = {
        Stopped = ">>",
        Breakpoint = "B ",
        BreakpointCondition = "B?",
        BreakpointRejected = "B!",
        LogPoint = ".>",
    },
    diagnostics = {
        Error = "E",
        Warn = "W",
        Hint = "H",
        Info = "I",
    },
    git = {
        added = "+",
        modified = "~",
        removed = "-",
        branch = "git:",
    },
    gitsigns = {
        signs = {
            add = "┃",
            change = "┃",
            delete = "_",
            topdelete = "‾",
            changedelete = "~",
            untracked = "┆",
        },
        signs_staged = {
            add = "┃",
            change = "┃",
            delete = "_",
            topdelete = "‾",
            changedelete = "~",
            untracked = "┆",
        },
    },
    indent = {
        char = "|",
    },
    folder = {},
    kinds = {},
    luasnip = {
        choice_node = "c",
    },
    mason = {
        package_installed = "[+]",
        package_pending = "[~]",
        package_uninstalled = "[-]",
    },
    render_markdown = {
        heading = {
            icons = { "1) ", "2) ", "3) ", "4) ", "5) ", "6) " },
            signs = { "# " },
            above = "▄",
            below = "▀",
        },
        code = {
            language_border = "█",
            above = "▄",
            below = "▀",
        },
        dash = "─",
        bullet = { "-", "*", "+", "~" },
        checkbox = {
            unchecked = "[ ] ",
            checked = "[x] ",
        },
        custom = {
            todo = "[ ] ",
        },
        quote = "|",
        table = { "┌", "┬", "┐", "├", "┼", "┤", "└", "┴", "┘", "│", "─" },
        callout = {
            note = "(i) ",
            tip = "(*) ",
            important = "(!!) ",
            warning = "/!\\ ",
            caution = "/!\\ ",
            abstract = "(:) ",
            summary = "(:) ",
            tldr = "(:) ",
            info = "(i) ",
            todo = "( ) ",
            hint = "(*) ",
            success = "(+) ",
            check = "(+) ",
            done = "(+) ",
            question = "(?) ",
            help = "(?) ",
            faq = "(?) ",
            attention = "/!\\ ",
            failure = "(-) ",
            fail = "(-) ",
            missing = "(-) ",
            danger = "(x) ",
            error = "(x) ",
            bug = "(!) ",
            example = ">> ",
            quote = ">> ",
            cite = ">> ",
        },
        link = {
            footnote = "[^] ",
            image = "[img] ",
            email = "@ ",
            hyperlink = "",
            wiki = "== ",
            custom = {
                web = "",
                apple = "",
                discord = "",
                github = "",
                gitlab = "",
                google = "",
                hackernews = "",
                linkedin = "",
                microsoft = "",
                neovim = "",
                reddit = "",
                slack = "",
                stackoverflow = "",
                steam = "",
                twitter = "",
                wikipedia = "",
                x = "",
                youtube = "",
                youtube_short = "",
            },
        },
        indent = "|",
    },
    statusline = {
        sep = "|",
    },
    winbar = {
        modified = "[+]",
        readonly = "[RO]",
        ellipsis = "...",
        lsp = "[L]",
    },
}

M.icons = vim.g.pretty and pretty or plain

return M
